### ISSUE TITLE
Device name not added after registration

### ISSUE THREAD

**Issue by okal** [bogdal/django-gcm#18]
Hi,

I'm sending a JSON payload of the following form

```javascript
'{"reg_id": "<registration id>", "dev_id": "<device id>", "name": "A Device"}'
```

Running `$./manage.py gcm_messenger --devices` gives me the following.

```
(#1) None
```

The device is registered, but the name is set to `None`, for some reason. Any idea why that might be happening?

PS: Thanks for the great work :-)

**Comment by bogdal** [comment]
Fixed in #22
