### ISSUE TITLE
Support for bulk push

### ISSUE THREAD

**Issue by mevinbabuc** [bogdal/django-gcm#23]
It would be really awesome if it had support for bulk push. If its already implemented, where can I get docs on using it.

Thanks,
Mevin

**Comment by bogdal** [comment]
Hi @mevinbabuc. `django-gcm` supports bulk push, but it looks like we don't have this in the documentation yet. The easiest way is to use `send_message` method of the device queryset. E.g:
```
Device.objects.all().send_message('my message')
```

Cheers!
