### ISSUE TITLE
Overriding the send function in api.GCMMessage

### ISSUE THREAD

**Issue by mevinbabuc** [bogdal/django-gcm#24]
I would like to add a few optional arguments to the 

        values = {
            'registration_ids': regs_id,
            'collapse_key': collapse_key,
            'data': data
        }

How can I do that ?. Is there an easy way to override this ?

**Comment by bogdal** [comment]
Yeah, additional parameters may be important so I have added the ability to easily add them. Check the new `1.0.6` version out.

An example of usage:
```
from gcm.models import get_device_model
Device = get_device_model()

Device.objects.all().send_message('my message', delay_while_idle=True, time_to_live=5)
```
All `kwargs` params are added to the `values` dict.

**Comment by mevinbabuc** [comment]
Thank you a lot for adding this feature in !

On 6 March 2015 at 03:32, Adam Bogdał <notifications@github.com> wrote:

> Yeah, additional parameters may be important so I have added the ability
> to easily add them. Check the new 1.0.6 version out.
>
> An example of usage:
>
> from gcm.models import get_device_model
> Device = get_device_model()
>
> Device.objects.all().send_message('my message', delay_while_idle=True, time_to_live=5)
>
> All kwargs params are added to the values dict.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bogdal/django-gcm/issues/24#issuecomment-77461673>.
>



-- 
Thank You
*Mevin Babu,** <http://in.linkedin.com/in/mevinbabuc>*
http://mevinbabuc.in/ <http://mevinbabuc.appspot.com/>
