### ISSUE TITLE
Failing to pip install django-gcm due to dependencies

### ISSUE THREAD

**Issue by devintm** [bogdal/django-gcm#27]
I have tried to install django-gcm but it's failing due to a dependency on django-tastypie.  I also tried to install django-tastypie first but django-gcm still fails to install.  Currently, django-gcm 1.0.6 is working and installing.  It's just 1.0.7 that is failing for me to install.

    $ pip install django-gcm
    Collecting django-gcm
    Downloading django-gcm-1.0.7.tar.gz
    Requirement already satisfied (use --upgrade to upgrade): django>=1.6 in /home/vagrant/virtualenvs/nextdrop/lib/python2.7/site-packages (from django-gcm)
    Collecting django-tastypie>=0.12.2-dev (from django-gcm)

    Could not find a version that satisfies the requirement django-tastypie>=0.12.2-dev (from django-gcm) (from versions: 0.9.6, 0.9.7, 0.9.9, 0.9.10, 0.9.11, 0.9.12, 0.9.13, 0.9.14, 0.9.15, 0.9.16, 0.10.0, 0.11.0, 0.11.1, 0.12.0, 0.12.1)
    No matching distribution found for django-tastypie>=0.12.2-dev (from django-gcm)

**Comment by bogdal** [comment]
Hi @devintm. Try to use the following command:
```
pip install django-gcm --process-dependency-links
``` 
The latest version of `django-tastypie` isn't released on pypi yet, so we have it in the [dependency links](https://github.com/bogdal/django-gcm/blob/develop/setup.py#L38) section.

**Comment by devintm** [comment]
Yes, --process-dependency-links switch  worked. Thank you.
