### ISSUE TITLE
Logging

### ISSUE THREAD

**Issue by DheerendraRathor** [bogdal/django-gcm#32]
Currently there is nothing logged in entire repository. There are only 2 singals and that are for register and unregister. I want to add Logging at various points like message sent, failure received, device_id and failing reason mapping etc. 

I'll create a PR if required.

**Comment by bogdal** [comment]
@DheerendraRathor feel free to create a PR. They are always welcome. Thanks.

**Comment by bogdal** [comment]
The new version `1.0.8` is available on pypi.
