### ISSUE TITLE
Saving device model on unregister endpoint

### ISSUE THREAD

**Issue by DheerendraRathor** [bogdal/django-gcm#34]
Hi,

Currently the unregister endpoint is saving the `dev_id` for marking them `inactive`. Now the issue is:
If some user decides to send false dev_id (without reg_id) to unregister endpoint, The `dev_id` will be stored with `reg_id = null`. Now if the same user again send the false `dev_id`, this will cause `IntegrityError: duplicate key value violates unique constraint "gcm_device_reg_id_key"
DETAIL:  Key (reg_id)=() already exists.`, which will send repeated mails to django site admin. 

I want to know your views on this.

**Comment by bogdal** [comment]
We should be able to unregister only the existing devices.

**Comment by bogdal** [comment]
Fixed in `1.1.0` version.
