### ISSUE TITLE
django-gcm issue with sending message

### ISSUE THREAD

**Issue by Chitrank-Dixit** [bogdal/django-gcm#39]
I have followed the django-gcm documentation to setup gcm for my project. I was experiencing problems while sending message to gcm registered device, I was able to send something to the gcm registered device but on the android device it was coming as null. Here is the link I am following

http://django-gcm.readthedocs.org/en/latest/sending_messages.html

so I changed this line
my_phone.send_message('my test message', collapse_key='something')

to
my_phone.send_message({'message':'my test message'}, collapse_key='something')

and it got working fine for me and I am receiving a proper message so I am suggesting a little change in the documentation so that others won't get into problems.

**Comment by bogdal** [comment]
Fixed in #40
