### ISSUE TITLE
Not compatible with django 1.9

### ISSUE THREAD

**Issue by Northshoot** [bogdal/django-gcm#41]
since dependency on tasty, the gcm is not compatible with 1.9 due to https://github.com/django-tastypie/django-tastypie/issues/1395

Moreover, as disscussed there, get_cache has been removed from django, which is used by tasty

It does work with version django-tastypie-0.12.2.dev0 which is not in the pip repo. The dependencies could be updated.

**Comment by Akcps** [comment]
unable to use django-gcm for the same reason

**Comment by bogdal** [comment]
`django-gcm 1.2.0` supports Django 1.9 :ship:
