### ISSUE TITLE
message omitted after space

### ISSUE THREAD

**Issue by ghost** [bogdal/django-gcm#8]
I am encountering an issue that when i send a message , the message string after a space is omitted.
e.g. if i send "check now"
Only check is being shown in the Dialog.

Edit : This is happening when i am sending messages from console.
There is no problem if i send messages from python manage.py shell.

**Comment by brisa123** [comment]
Hi,
As soon as i type "python manage.py gcm_messenger --devices "  on ubuntu console,
i get an empty device list.
Device list : <nothing>.
why is it so?
